### ISSUE TITLE
map files

### ISSUE THREAD

**Issue by celinasjose** [TomSexton00/4See#1]
How do I generate the map files from my 4C data?

Thanks

**Comment by TomSexton00** [comment]
Hello. Are you asking how to generate the .cis files from the sequencing data, or how to export the 4See profiles as bedgraph files? Or something else?
Thanks for any precisions.
Best,
 Tom

**Comment by celinasjose** [comment]
Hi!
To create the file in cis format, I sould use the coord2frag.pl script.
One of the input files of this script is a reads file with map format. 
How do you generate the reads file from 4C-seq data aligned?

Cheers,

**Comment by TomSexton00** [comment]
Hi,
 The "map" format is a standard output generated by Bowtie1. Each read follows this format: K00201:368:HFMG5BBXY:2:1101:4503:1420 1:N:0:15  +       chr3    34660499        GATCTGCGAGCAGCCCGAGAGCCAAAG     -AAJ<<<<A--7A-A--7<--7FA-<<   0       7:A>G,16:C>G

The coord2frag.pl script just requires a "chr", "coordinate" and "strand" column from the text file, as well as one instance of the actual sequence, so that the read length can be deduced. In its current form, this script is hard-wired to look for specific columns within this fixed format (columns 2, 3, 4 and 5 to be precise).

What tool are you using to align your fastq reads, and which output format does that take? I can look for a fix so that you are able to generate your own .cis files.

Best,
  Tom

**Comment by TomSexton00** [comment]
Hi, I see that you haven't replied to this, so I hope you were able to solve your problem. I will close this issue now; feel free to open a new one if you are still having problems.
