### ISSUE TITLE
Possible to not normalize plots if n > 1?

### ISSUE THREAD

**Issue by jonasungerback** [TomSexton00/4See#2]
Hello,

first and foremost, thank you for a nice tool making 4C visualization a breeze. I do however, have one question comment: The way I understand it, if you plot more than one condition the data is normalized (see below). Would it be possible to have the normalization step optional? I have a scenarion where I want to create cis-files from an object already normalized with a different tool (R.4Cker in this case) but when I take the exact same numbers that I plot there and try to plot them with 4see it looks quite different. I assume this is due to normalization of already normalized data. If I am wrong and this already exists, I apologize but otherwise it would be nice to have normalization as an option:

Best,
Jonas

`if(length(data)>1) {
		for (i in 1:length(settings)) {
			sel = settings[[i]][["indices"]]
			for (j in 1:length(sel)) {
				tmp=data[[sel[j]]]
				tmp=tmp[tmp$coord>vp.pos-1500000 & tmp$coord<vp.pos+1500000,]
				if(is.null(table)) {
					table=tmp
					colnames(table)[2]=names(data)[sel[j]]
				} else {
					colnames(tmp)[2]=names(data)[sel[j]]
					table=merge(table,tmp)
				}
			}
		}
		n=normalizeBetweenArrays(table[,-1])
		for (i in 2:dim(table)[2]) {
			table[,i]=n[,i-1]
		}
	} else {
		table=data[[1]]
		colnames(table)[2]=names(data)[1]
	}`

**Comment by jonasungerback** [comment]
I assume it should be `n=normalizeBetweenArrays(table[,-1])` that should be optional to be more specific.

**Comment by TomSexton00** [comment]
Hi,
  You are right that this normalisation is "hard-wired" into the code. I will try to set up another version where the normalisation is optional, but this is heavily discouraged if you have not already normalised the data yourself. And note that the normalisation must be across the samples, not just within one sample, otherwise things like sequencing depth will heavily skew the results.

**Comment by jonasungerback** [comment]
This I absolutely understand and of course the normalization should be the default but it would be a nice option. Thank you!

**Comment by TomSexton00** [comment]
Please find attached a beta-version of the advanced 4See browser. If you are happy with it, I will put it onto github proper.

Everything is the same, except for a new button on the main browser ("Advanced"). This allows you to toggle off normalization (default setting is on), and if you decide to keep the normalization to alter the window size over which the normalization occurs (default 1.5 Mb, previously hard-wired). Of course, to give similar results to your previous 4Cker results, you need to make sure to have a compatible .cis file, and to bear in mind things like sliding window sizes, etc.

Hope this help
[4See_adv.zip](https://github.com/TomSexton00/4See/files/7397024/4See_adv.zip)
s.

**Comment by jonasungerback** [comment]
Thank you! It works like a charm and I think it is a beautiful addition. By easy being able to toggle it on and off it is also an easy way to get a feel for the data. I have another related question (so not an issue). I am new to 4c analysis but what are the assumptions behind normalizations. I know that in RNA/ATAC/ChIP-seq you assume that genome/transcriptome wide you have approx the same genes/regions that goes up and down but in 4c-seq I assume this is not the case. Say that I want to compare two samples where the average interaction frequency near the bait is down 2 or 10-fold for that matter, how would normalization affect that comparison?

I know that in this case normalizeBetweenArrays is being applied (which I assume was developed for microarrays). I am not very familiar with these normalizations and have to read up a bit but can it obscure real differences in 4c-seq data?

**Comment by TomSexton00** [comment]
In 4C, the strongest signal (by far) is the interactions just proximal to the bait, although the "decay" curve depends heavily on the exact bait and locus studied. Some form of normalization for comparison across samples is required to account for differences in sequencing depth (and also prevalence of PCR duplicates, which are huuuuge for conventional 4C-seq). Many groups scale their reads by total numbers of reads, or total numbers of cis reads, which is appropriate for "genome-wide" analyses, particularly when the different conditions cause gross changes in interchromosomal or very long-range contacts (e.g. silent vs highly active gene). In our hands, we find that we get more robust performance when focussing on shorter-to-mid range interactions (default <1.5 Mb; the premise of visualization with 4See, since very long-range and trans interactions are not supported) by performing quantile normalization over the range that interests us.

As always, if your conclusions are supported by trying different normalization approaches, one is more confident with the results!

Hope this helps.

**Comment by jonasungerback** [comment]
I know I comment on a closed thread but it is still related to this issue. Even though the turn of button works nicely I get the following error when trying to save the image:

`Error in `[.data.frame`(tmp, tmp$coord > vp.pos - normwin & tmp$coord <  : 
  argument "normwin" is missing, with no default`

This is nothing that happens in the original version of the software. Only the advanced.

Jonas
